### ISSUE TITLE
more precise requirement

### ISSUE THREAD

**Issue by eddie1516** [CUN-bjy/policy-distillation-baselines#12]
requirement.txt dosen‘t give the accurate versions of some python packages. Some packages are updated so that the project can't run. Could you please update the requirement.txt? Thank you!

**Comment by Black0Moonlight** [comment]
> requirement.txt dosen‘t give the accurate versions of some python packages. Some packages are updated so that the project can't run. Could you please update the requirement.txt? Thank you!

try it:

python==3.7
gym==0.19.0
tensorboardX
torch
stable-baselines3[extra,tests,docs]==1.1.0
pybullet==2.7.8
optuna
pyyaml>=5.1
sb3-contrib==1.0.0
